#!/bin/bash

printf "\n\nGenerate Key Pair\n\n"
openssl genrsa -aes128 -out private.key 1024

printf "\n\nSeparate Public and Private Key\n\n"
openssl rsa -in private.key -outform PEM -pubout -out public.key
